packageExtensions:
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@material/mwc-button@*":
    dependencies:
      "@material/mwc-base": "*"
  "@material/mwc-icon-button@*":
    dependencies:
      "@material/mwc-base": "*"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
