yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  # https://github.com/firebase/firebase-js-sdk/issues/3707
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"

  # https://github.com/material-components/material-web/issues/2994
  "@material/mwc-button@*":
    dependencies:
      "@material/mwc-base": "*"
  "@material/mwc-icon-button@*":
    dependencies:
      "@material/mwc-base": "*"